name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.x"
      - name: Restore packages
        run: dotnet restore src/Randactyl.BlazorWasm/Randactyl.BlazorWasm.csproj --nologo
      - name: Build project
        run: dotnet build src/Randactyl.BlazorWasm/Randactyl.BlazorWasm.csproj -c Release --nologo
      - name: Publish project
        run: dotnet publish src/Randactyl.BlazorWasm/Randactyl.BlazorWasm.csproj -c Release -o release --nologo
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
